# Generated by Django 5.1.3 on 2026-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0012_attendance_branch_alter_attendance_technology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="trainer_name",
            field=models.CharField(
                choices=[
                    ("MR. AMAN (DATA SCIENCE)", "MR. AMAN (DATA SCIENCE)"),
                    ("MR. ABDUL (DATA ANALYTICS)", "MR. ABDUL (DATA ANALYTICS)"),
                    ("MR. PRASHANT (GRAPHIC)", "MR. PRASHANT (GRAPHIC)"),
                    ("MR. SAGAR (CLOUD)", "MR. SAGAR (CLOUD)"),
                    ("MR. RAJESH (JAVA)", "MR. RAJESH (JAVA)"),
                    ("MR. HEMANT (ETHICAL)", "MR. HEMANT (ETHICAL)"),
                    ("MRS. MAMTA (MERN)", "MRS. MAMTA (MERN)"),
                    ("MR. SOUVIK (CYBER)", "MR. SOUVIK (CYBER)"),
                    ("MRS NITI GUPTA (PD)", "MRS NITI GUPTA (PD)"),
                    ("AMAN KHAN (DIGITAL MARKETING)", "AMAN KHAN (DIGITAL MARKETING)"),
                    ("MR. RUPINDER (AUTOCAD)", "MR. RUPINDER (AUTOCAD)"),
                    ("MR. AMAN SIR (FLUTTER)", "MR. AMAN SIR (FLUTTER)"),
                    ("MR. PRATEEK (WEB-DESIGN)", "MR. PRATEEK (WEB-DESIGN)"),
                    ("MR. TARUN (MERN)", "MR. TARUN (MERN)"),
                    (
                        "ABHISHEK UPADHYAY (DATA SCIENCE)",
                        "ABHISHEK UPADHYAY (DATA SCIENCE)",
                    ),
                    ("SOURABH (JAVA )", "SOURABH (JAVA )"),
                    ("MR. KUNAL (CYBER SECURITY)", "MR. KUNAL (CYBER SECURITY)"),
                ],
                max_length=100,
            ),
        ),
    ]
