# Generated by Django 5.1.3 on 2026-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_alter_feedback_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="placement_drive_started",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
