# Generated by Django 5.1.3 on 2026-04-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_batch_email_sent_alter_batch_batch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="batch_name",
            field=models.CharField(
                choices=[
                    ("PYTHON", "PYTHON"),
                    ("POWER BI", "POWER BI"),
                    ("EXCEL", "EXCEL"),
                    ("Stats", "Stats"),
                    ("SQL", "SQL"),
                    ("TABLEAU", "TABLEAU"),
                    ("MACHINE LEARNING", "MACHINE LEARNING"),
                    ("NLP", "NLP"),
                    ("GEN AI", "GEN AI"),
                    ("CORE JAVA", "CORE JAVA"),
                    ("ADVANCED JAVA", "ADVANCED JAVA"),
                    ("REACT JS", "REACT JS"),
                    ("NODE JS", "NODE JS"),
                    ("MONGODB", "MONGODB"),
                    ("DATA SCIENCE", "DATA SCIENCE"),
                    ("MERN/MEAN STACK", "MERN/MEAN STACK"),
                    ("CLOUD COMPUTING", "CLOUD COMPUTING"),
                    ("DATA ANALYTICS", "DATA ANALYTICS"),
                    ("OTHERS", "OTHERS"),
                ],
                default="OTHERS",
                max_length=100,
            ),
        ),
    ]
