# Generated by Django 5.1.3 on 2026-05-05 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_batch_batch_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"verbose_name_plural": "Batches"},
        ),
        migrations.AddField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Closed", "Closed")],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="branch",
            field=models.CharField(
                choices=[
                    ("Vikaspuri", "Vikaspuri"),
                    ("Pitampura", "Pitampura"),
                    ("South Ex", "South Ex"),
                    ("Noida", "Noida"),
                    ("Gurgaon", "Gurgaon"),
                    ("Ghaziabad", "Ghaziabad"),
                ],
                default="Vikaspuri",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="batch_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="batch",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="dashboard.trainer",
            ),
        ),
    ]
